language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
install:
  - travis_wait pip install -r travis-requirements.txt
  - pip install .
  - python setup.py build_ext -i
script:
  - pytest --cov=untwist --pep8 untwist
